<?php

namespace AppBundle\Repository;

use Doctrine\ORM\EntityRepository;



/**
 * PersonRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class PersonRepository extends EntityRepository{
    //maak nieuwe persoon aan
    public function createPerson($person){
        $this->getEntityManager()->persist($person);
        $this->getEntityManager()->flush();
    }

    //update persoon
    public function updatePerson($person){
        $this->getEntityManager()->persist($person);
        $this->getEntityManager()->flush();
    }

    //delete persoon
    public function deletePerson($person){
        $this->getEntityManager()->remove($person);
        $this->getEntityManager()->flush();
    }

    //zoek personen met rol
    public function findAllPersonsWithRole($role)
    {
        $query = $this->createQueryBuilder('p')
            ->where('p.role LIKE :role')
            ->setParameter('role', $role)
            ->getQuery();
        $members = $query->getResult();
        return $members;
    }

    //geef alle gebruikers terug
    public function findAllUser(){
        return $this->findAll();
    }

    //geef alle leden
    public function findAllMembers(){
        return $this->findAllPersonsWithRole('["ROLE_MEMBER"]');
    }

    //geef alle admins
    public function findAllAdmin(){
        return $this->findAllPersonsWithRole('["ROLE_ADMIN"]');
    }

    public function findByUsername($username)
    {
        $query = $this->createQueryBuilder('p')
            ->where('p.loginName LIKE :username')
            ->setParameter('username', $username)
            ->getQuery();
        $member = $query->getResult();

        return $member;
    }

}
