<?php

namespace AppBundle\Repository;

/**
 * RegistrationRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */

use AppBundle\Entity\Registration;

class RegistrationRepository extends \Doctrine\ORM\EntityRepository
{
    public function createRegistration($lid, $les, $payment){

        $registration = new Registration();
        $registration->setLesson($les);
        $registration->setMember($lid);
        $registration->setPayment($payment);

        $this->getEntityManager()->persist($registration);
        $this->getEntityManager()->flush();

    }

}
