<?php

namespace AppBundle\Repository;

/**
 * TrainingRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */

use Doctrine\ORM\EntityRepository;

class TrainingRepository extends EntityRepository
{
    //maak nieuwe aan
    public function createTraining($training){

        if($training){
            $this->getEntityManager()->persist($training);
            $this->getEntityManager()->flush();
        }
    }

    //training zoeken
    public function findTraining($id){
        return $this->find($id);
    }

    //training verwijderen
    public function deleteTraining($id){
         $training = $this->find($id);

         if($training){
             $this->getEntityManager()->remove($training);
             $this->getEntityManager()->flush();
         }
    }

    //training updaten
    public function updateTraining($training){

        if($training){
            $this->getEntityManager()->persist($training);
            $this->getEntityManager()->flush();
        }
    }

    //return order result
    public function ordered(){
        return
            $this->getEntityManager()
                ->createQuery('SELECT t FROM AppBundle:Training t ORDER BY t.name ASC')
                ->getResult();
    }
}
