<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerRcuzzje\appDevDebugProjectContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerRcuzzje/appDevDebugProjectContainer.php') {
    touch(__DIR__.'/ContainerRcuzzje.legacy');

    return;
}

if (!\class_exists(appDevDebugProjectContainer::class, false)) {
    \class_alias(\ContainerRcuzzje\appDevDebugProjectContainer::class, appDevDebugProjectContainer::class, false);
}

return new \ContainerRcuzzje\appDevDebugProjectContainer([
    'container.build_hash' => 'Rcuzzje',
    'container.build_id' => '9bd7045b',
    'container.build_time' => 1554374917,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerRcuzzje');
