<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerVcs15oo\appDevDebugProjectContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerVcs15oo/appDevDebugProjectContainer.php') {
    touch(__DIR__.'/ContainerVcs15oo.legacy');

    return;
}

if (!\class_exists(appDevDebugProjectContainer::class, false)) {
    \class_alias(\ContainerVcs15oo\appDevDebugProjectContainer::class, appDevDebugProjectContainer::class, false);
}

return new \ContainerVcs15oo\appDevDebugProjectContainer([
    'container.build_hash' => 'Vcs15oo',
    'container.build_id' => '24ea082a',
    'container.build_time' => 1553599839,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerVcs15oo');
