# To get started with security, check out the documentation:
# https://symfony.com/doc/current/security.html
security:

    # https://symfony.com/doc/current/security.html#b-configuring-how-users-are-loaded
    providers:
        chain_provider:
            chain:
                providers: [in_memory, user_db]
        in_memory:
            memory:
                users:
                    ryan:
                        password: $2y$12$0VYtpI.QV8ZOkeTJbYhxPOnkWIQImWfi6aMjP4uC72lpJgYIYQX0u
                        roles: 'ROLE_MEMBER'
                    admin:
                        password: $2y$12$Nh2957IPt.XpNK1RBn.QLeHz7Yk1aqUFgvulqn/IUM0Hx9qUZ5jIa
                        roles: 'ROLE_ADMIN'
                    dev:
                        password: $2y$12$Nh2957IPt.XpNK1RBn.QLeHz7Yk1aqUFgvulqn/IUM0Hx9qUZ5jIa
                        roles: 'ROLE_DEV'
                    test:
                        password: $2y$12$6xaiKvf4fFNaRzDlf0ZCLOJGKFd.efxeYhVoOabWEZwCexmPpvKZC
                        roles: 'ROLE_ADMIN'
        user_db:
            entity:
                class: AppBundle\Entity\Person
                property: loginName

    encoders:
        Symfony\Component\Security\Core\User\User:
            algorithm: 'bcrypt'
            cost:      12

        AppBundle\Entity\Person: plaintext

    firewalls:
        # disables authentication for assets and the profiler, adapt it according to your needs
        dev:
            pattern: ^/(_(profiler|wdt)|css|images|js)/
            security: false

        main:
            anonymous: ~
            http_basic: ~
            provider: chain_provider
            form_login:
                login_path: login
                check_path: login
            logout:
                path: /logout
                target: /
            # activate different ways to authenticate

            # https://symfony.com/doc/current/security.html#a-configuring-how-your-users-will-authenticate
#            http_basic: ~

            # https://symfony.com/doc/current/security/form_login_setup.html
            #form_login: ~

    role_hierarchy:
        ROLE_ADMIN: [ROLE_USER, ROLE_ALLOWED_TO_SWITCH]
        ROLE_DEV: [ROLE_ADMIN, ROLE_ALLOWED_TO_SWITCH, ROLE_USER]

    access_control:
        # require ROLE_ADMIN for /admin*
        - { path: ^/trainer/new, roles: ROLE_DEV }
        - { path: ^/trainer/list, roles: ROLE_ADMIN }
        - { path: ^/training/list, roles: ROLE_ADMIN }
        - { path: ^/training/*, roles: ROLE_DEV }
#        - { path: ^/, roles: IS_AUTHENTICATED_ANONYMOUSLY }
#        - { path: ^/, roles: ROLE_USER }